# Generated by Django 2.2.2 on 2019-06-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, upload_to='imagenes_articulos', verbose_name='imagen'),
        ),
    ]
