# Generated by Django 2.2.2 on 2019-07-03 00:31

from django.db import migrations, models
import django.db.models.deletion
import inicio.models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20190629_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ('nombre_foto',)},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='foto_ptr',
        ),
        migrations.AddField(
            model_name='articulo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foto',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inicio.Articulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, upload_to='imagines_articulos', verbose_name='imagen'),
        ),
    ]
