# Generated by Django 2.2.2 on 2019-07-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20190703_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(blank=True, max_length=500, upload_to='imagenes_articulos', verbose_name='imagen'),
        ),
    ]
