# Generated by Django 2.2.2 on 2019-07-03 01:41

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20190703_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_foto', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, max_length=500, upload_to='imagenes_articulos', verbose_name='imagen')),
                ('cropping', image_cropping.fields.ImageRatioField('foto', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recorte visible')),
                ('articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='imagenes_articulos', to='inicio.Articulo')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Galería',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
