# Generated by Django 2.2.2 on 2019-07-08 21:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_auto_20190704_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
